# Generated by Django 4.1.7 on 2023-04-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_category_ai_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ai',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Most Popular Neuronetworks', 'verbose_name_plural': 'Most Popular AIs'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Category'),
        ),
    ]
